[tool.bumpversion]
current_version = "0.1.0"  # 這裡舉例目前的版號
# parse 增加了可以用來辨識 -alpha.1, -beta.2, -rc.1 的正規表示式
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(?:-(?P<stage>alpha|beta|rc)\\.(?P<build>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}-{stage}.{build}", # 優先匹配帶有 stage 的格式
    "{major}.{minor}.{patch}"                  # 如果沒有 stage，就使用正式版格式
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = true
message = "chore(release): bump version {current_version} → {new_version}"
moveable_tags = []
commit_args = ""
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []
allow_shell_hooks = false

[tool.bumpversion.parts.stage]
type = "part"
values = ["alpha", "beta", "rc"]

[tool.bumpversion.parts.build]
type = "numeric"
first_value = "1"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'