name: Manual Trigger Release

on:
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Choose the type of version bump: patch, minor, or major'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  execute-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Bump version
        id: bump_step
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_COMMIT: "true"
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump_type }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release Page
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.bump_step.outputs.new_version }}
          name: Release v${{ steps.bump_step.outputs.new_version }}
          generate_release_notes: true
          draft: false
          prerelease: false
      
      - name: Deploy to Coolify
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
      
      - name: Trigger docs rebuild
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.DOCS_REPO_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/DiscordHubDev/dchubs-api-docs/dispatches \
            -d '{"event_type":"openapi-updated"}'